_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 6
                - 8
                - 9
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 6
                - 8
                - 9
                - 53
                - 55
                - 103
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: gelu
batch_size:
    value: 64
d_model:
    value: 1024
dropout:
    value: 0.4673825888610368
learning_rate:
    value: 0.0001
n_heads:
    value: 4
